import { getCloudflareContext } from "@opennextjs/cloudflare";
import { authenticate, type AdminEnv } from "@/lib/admin/security";
import { page } from "@/lib/admin/ui";

const headers = { customers:["Account Number","Full Name","Company","Mobile","Email","Address","Notes","Created","Updated"], shipments:["Tracking Number","Account Number","Customer Name","Service Type","Origin Warehouse","Warehouse Received Date","Departure Date","CBM","Weight KG","Status","Estimated Arrival","Actual Arrival","Tracking Remarks","KargoDoor Freight Charge","Ni Hao Freight Cost","Delivery Charge","Payment Status","Created","Updated"] };
const cell = (value: unknown) => { const text=String(value??"").replace(/^([=+\-@])/, "'$1"); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g,'""')}"` : text; };
const file = (name:string, columns:string[], rows:Record<string,unknown>[]) => new Response("\ufeff"+[columns.join(","),...rows.map(row=>columns.map(key=>cell(row[key])).join(","))].join("\r\n"),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${name}"`,"Cache-Control":"no-store"}});

export async function GET(request: Request) {
 const {env}=await getCloudflareContext(); const admin=env as unknown as AdminEnv; const user=await authenticate(request,admin); const action=new URL(request.url).searchParams.get("download"); const date=new Date().toISOString().slice(0,10);
 if(action==="customer-template") return file("KargoDoor-Customer-Import-Template.csv",headers.customers.slice(0,7),[]);
 if(action==="shipment-template") return file("KargoDoor-Shipment-Import-Template.csv",headers.shipments.filter(x=>!["Customer Name","Created","Updated"].includes(x)),[]);
 if(action==="customers") { const rows=(await admin.ADMIN_DB.prepare("SELECT customer_code AS 'Account Number', full_name AS 'Full Name', company_name AS Company, mobile AS Mobile, email AS Email, address AS Address, notes AS Notes, created_at AS Created, updated_at AS Updated FROM customers ORDER BY created_at").all<Record<string,unknown>>()).results; return file(`KargoDoor-Customers-${date}.csv`,headers.customers,rows); }
 if(action==="shipments") { const rows=(await admin.ADMIN_DB.prepare("SELECT s.tracking_number AS 'Tracking Number',c.customer_code AS 'Account Number',c.full_name AS 'Customer Name',s.service_type AS 'Service Type',s.china_warehouse AS 'Origin Warehouse',s.warehouse_received_date AS 'Warehouse Received Date',s.departure_date AS 'Departure Date',s.cbm AS CBM,s.weight_kg AS 'Weight KG',s.status AS Status,s.estimated_arrival AS 'Estimated Arrival',s.actual_arrival AS 'Actual Arrival',s.tracking_remarks AS 'Tracking Remarks',s.shipping_charge AS 'KargoDoor Freight Charge',s.nihao_cost AS 'Ni Hao Freight Cost',s.delivery_charge AS 'Delivery Charge',s.payment_status AS 'Payment Status',s.created_at AS Created,s.updated_at AS Updated FROM shipments s JOIN customers c ON c.id=s.customer_id ORDER BY s.created_at").all<Record<string,unknown>>()).results; return file(`KargoDoor-Shipments-${date}.csv`,headers.shipments,rows); }
 return page("Import / Export",`<section><h2>Export data</h2><p><a class="button" href="?download=customers">Export Customers CSV</a> <a class="button" href="?download=shipments">Export Shipments CSV</a></p></section><section><h2>Download templates</h2><p><a href="?download=customer-template">Customer CSV Template</a> · <a href="?download=shipment-template">Shipment CSV Template</a></p><p class="muted">CSV files can be opened in Excel, Numbers, or Google Sheets.</p></section>`,user.name);
}
