import assert from "node:assert/strict";
import test from "node:test";
import { customerQuotationPdf, defaultQuotationTerms } from "../../lib/admin/quotation-pdf";

const saved={quotation_number:"KD-Q-2026-001",quotation_date:"2026-09-10",freight_type:"Sea Freight",final_amount:125000,customer_snapshot:JSON.stringify({name:"Ada Customer",company:"Example Trading",mobile:"09171234567",email:"ada@example.com",address:"Manila"}),cargo_snapshot:JSON.stringify({description:"Household wares",category:"General Cargo",quantity:99,unitType:"boxes",length:40,width:30,height:20,measurementUnit:"cm",cbm:.024,weight:12,origin:"Guangzhou",originWarehouse:"China Warehouse"}),pricing_snapshot:JSON.stringify({density:500,rateBasis:"PHP 520 / CBM",formula:"0.024 CBM x PHP 520"}),backend_cost:999999,nihao_cost:999999,gross_margin:999999,override_reason:"Internal reason",notes:"Admin notes"};
test("customer quotation PDF follows the branded saved-data template",()=>{const pdf=new TextDecoder().decode(customerQuotationPdf(saved)),date=pdf.indexOf("Date: 2026-09-10"),number=pdf.indexOf("Quotation No.: KD-Q-2026-001"),hiddenCjk="\u91c7\u8d2d \u00b7 \u8fd0\u8f93 \u00b7 \u6536\u8d27";assert.ok(pdf.startsWith("%PDF-1.4"));assert.ok(date>=0&&number>date);for(const value of ["KargoDoorPH","QUOTATION","Ada Customer","CARGO DETAILS","Category: General Cargo","Quantity / Packages: 1 package","Dimensions \\(L \\327 W \\327 H\\)","SHIPPING CALCULATION","Density: 500.00 kg/CBM","Applicable Rate / Basis: PHP 520 / CBM","ESTIMATED ALL-IN RATE","TERMS AND CONDITIONS","Admin notes","+63 917 157 7370","+63 908 889 0664","support@kargodoorph.com","www.kargodoorph.com","facebook.com/KargoDoorPH","@kargodoorph","SOURCE \\267 SHIP \\267 RECEIVE"])assert.ok(pdf.includes(value));assert.ok(!pdf.includes(hiddenCjk));for(const forbidden of ["999999","Internal reason","backend_cost","nihao_cost","gross_margin","Quantity / Packages: 99"])assert.ok(!pdf.includes(forbidden));});
test("quotations without saved terms use the editable standard terms",()=>{const pdf=new TextDecoder().decode(customerQuotationPdf({...saved,notes:null}));assert.ok(pdf.includes("TERMS AND CONDITIONS"));for(const line of ["Incoterm: FCA - KargoDoor Origin Warehouse","Service Coverage: Origin Warehouse > Manila Customs Clearance >"])assert.ok(pdf.includes(line));assert.ok(defaultQuotationTerms.includes("Incoterm"));});
test("an intentionally empty Terms and Conditions field removes the standard terms",()=>{const pdf=new TextDecoder().decode(customerQuotationPdf({...saved,notes:""}));assert.ok(pdf.includes("TERMS AND CONDITIONS"));assert.ok(!pdf.includes("Incoterm: FCA - KargoDoor Origin Warehouse"));assert.ok(!pdf.includes("Service Coverage: Origin Warehouse > Manila Customs Clearance >"));});
test("customer quotation PDF is a single A4 page",()=>{const pdf=new TextDecoder().decode(customerQuotationPdf(saved));assert.match(pdf,/\/MediaBox \[0 0 595 842\]/);assert.match(pdf,/\/Count 1/);});
