import { randomBytes, randomUUID } from "node:crypto";
import type { D1Database } from "@cloudflare/workers-types";
import { customerPasswordHash, normalizeCustomerEmail } from "@/lib/customer/security";
import { AdminError } from "./security";
export type Portal={id:string;login_email:string;enabled:number;password_state:"temporary"|"active"};
export const portalFor=(db:D1Database,id:string)=>db.prepare("SELECT id,login_email,enabled,password_state FROM customer_accounts WHERE customer_id=?").bind(id).first<Portal>();
export const portalStatus=(p:Portal|null)=>!p?"NOT ACTIVATED":!p.enabled?"DISABLED":p.password_state==="temporary"?"TEMPORARY PASSWORD":"ACTIVE";
const temp=()=>randomBytes(18).toString("base64url");
async function setTemp(db:D1Database,p:Portal,enabled=1){const password=temp(),salt=randomBytes(32).toString("hex"),now=new Date().toISOString();await db.prepare("UPDATE customer_accounts SET password_hash=?,password_salt=?,password_algorithm='scrypt',password_n=32768,password_r=8,password_p=1,password_key_length=64,enabled=?,password_state='temporary',updated_at=? WHERE id=?").bind(customerPasswordHash(password,salt),salt,enabled,now,p.id).run();await db.prepare("DELETE FROM customer_sessions WHERE customer_account_id=?").bind(p.id).run();return password;}
export async function createPortal(db:D1Database,customerId:string,emailValue:unknown){const email=normalizeCustomerEmail(String(emailValue??""));if(!email)throw new AdminError("This customer's email must be added and verified before creating portal access.");if(await portalFor(db,customerId))throw new AdminError("Customer portal account already exists.");if(await db.prepare("SELECT id FROM customer_accounts WHERE login_email=?").bind(email).first())throw new AdminError("This email is already assigned to another customer portal account.",409);const password=temp(),salt=randomBytes(32).toString("hex"),now=new Date().toISOString();await db.prepare("INSERT INTO customer_accounts (id,customer_id,login_email,password_hash,password_salt,password_algorithm,password_n,password_r,password_p,password_key_length,enabled,password_state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(randomUUID(),customerId,email,customerPasswordHash(password,salt),salt,"scrypt",32768,8,1,64,1,"temporary",now,now).run();return{email,password};}
export async function resetPortal(db:D1Database,id:string,reenable=false){const p=await portalFor(db,id);if(!p)throw new AdminError("Customer portal account has not been created.");return{email:p.login_email,password:await setTemp(db,p,reenable?1:p.enabled)};}
export async function disablePortal(db:D1Database,id:string){const p=await portalFor(db,id);if(!p)throw new AdminError("Customer portal account has not been created.");await db.prepare("UPDATE customer_accounts SET enabled=0 WHERE id=?").bind(p.id).run();await db.prepare("DELETE FROM customer_sessions WHERE customer_account_id=?").bind(p.id).run();}
