"use client";

import { useId, useState } from "react";
import { Footer, Header } from "@/components/site-chrome";

const faqs = [
  { question: "What is the complete KargoDoor shipping process?", answer: <ol className="kd-faq-steps"><li><strong>1 — SOURCE &amp; PURCHASE</strong><span>Find your preferred supplier in China and purchase your goods.</span></li><li><strong>2 — CONTACT KARGODOOR</strong><span>Contact KargoDoor <b>before your supplier ships</b> so we can confirm your shipment details.</span></li><li><strong>3 — WAREHOUSE ASSIGNMENT</strong><span>We’ll confirm the appropriate warehouse for your shipment. Available locations include <b>Guangzhou, Yiwu, Shishi, Hong Kong, and Taiwan</b>.</span></li><li><strong>4 — CARGO CODE / PACKAGE LABEL</strong><span>We’ll provide your unique <b>KargoDoor Cargo Code / Package Label</b>. Make sure your supplier attaches it to <b>EVERY package</b> before shipping.</span></li><li><strong>5 — WAREHOUSE RECEIVING</strong><span>Your supplier sends the goods to the assigned warehouse. Once received, your packages are <b>identified, measured, and verified</b>.</span></li><li><strong>6 — INTERNATIONAL SHIPPING</strong><span>Your cargo is shipped to the Philippines via <b>Sea or Air Freight</b>. We handle the applicable <b>international freight, customs clearance, duties, taxes, and processing</b>.</span></li><li><strong>7 — TRACKING &amp; ARRIVAL</strong><span>We provide available shipment information and updates along the way. We’ll notify you when your cargo arrives in the Philippines and is ready for release.</span></li><li><strong>8 — RECEIVE</strong><span>Receive your cargo through our <b>Metro Manila Warehouse</b>. Door-to-door delivery may also be arranged where available for an <b>applicable additional fee</b>.</span></li></ol> },
  { question: "What are your package tiers, and how much is 1 CBM?", answer: <><p>For <b>Sea Freight</b>, our promotional package rates are:</p><ul className="kd-faq-list"><li><b>KD Mini</b> — Up to 0.01 CBM: <b>₱250</b></li><li><b>KD Lite</b> — Above 0.01 to 0.05 CBM: <b>₱750</b></li><li><b>KD Plus</b> — Above 0.05 to 0.125 CBM: <b>₱1,400</b></li><li><b>KD Standard</b> — Above 0.125 CBM: <b>₱8,000/CBM</b>, minimum <b>₱1,700</b></li><li><b>KD Max</b> — Above 425 kg: <b>₱21/kg</b>, subject to the applicable rate calculation.</li></ul><p><b>1 CBM = 1 m × 1 m × 1 m.</b></p><p>Final CBM is based on verified warehouse measurements and may differ from your estimate.</p></> },
  { question: "Which warehouse should my supplier send my goods to?", answer: <><p>Please <b>contact KargoDoor before your supplier ships your goods</b>. We’ll confirm the appropriate warehouse for your shipment.</p><p>Our partner warehouse locations include <b>Guangzhou, Yiwu, Shishi, Hong Kong, and Taiwan</b>.</p><p>We’ll also provide your <b>KargoDoor Cargo Code / Package Label</b>, which must be attached to <b>EVERY package</b> so your shipment can be properly identified and processed.</p></> },
  { question: "What is included in KargoDoor's all-in shipping rate?", answer: <><p>Our all-in shipping rate covers the applicable <b>international freight, customs clearance, duties, taxes, and processing</b> from the assigned warehouse to the Philippines.</p><p>Door-to-door delivery may also be arranged where available for an <b>additional applicable fee</b>.</p></> },
  { question: "How long does shipping take?", answer: <><p><b>Sea Freight:</b> approximately <b>21–30 days</b></p><p><b>Air Freight:</b> approximately <b>3–7 days</b></p><p>Transit times are estimates and may vary depending on shipment schedules, customs processing, weather, holidays, and other circumstances beyond our control.</p></> },
  { question: "What items are restricted or prohibited?", answer: <><p>Certain items may be <b>restricted, prohibited, or require special handling or documentation</b> depending on the product, shipping method, and applicable regulations.</p><p>Please contact KargoDoor <b>before purchasing or shipping</b> items such as batteries, liquids, chemicals, food, medicines, cosmetics, branded goods, hazardous materials, or other regulated products.</p><p>When in doubt, <b>send us the product details or a photo first</b> so our team can confirm whether it can be accepted.</p></> },
  { question: "Can I track my shipment?", answer: <><p>Yes. KargoDoor can provide available <b>shipment information and status updates</b> during the shipping process.</p><p>We’ll also notify you when your cargo has arrived in the Philippines and is ready for release.</p></> },
  { question: "What payment methods do you accept?", answer: <><p>We currently accept:</p><p><b>GCash</b></p><p><b>Bank Transfer</b></p><p>Payment instructions and account details will be provided directly by the KargoDoor team when needed.</p></> },
  { question: "Is KargoDoor PH a legitimate shipping service?", answer: <><p>KargoDoor PH works with an established logistics backend and partner warehouse network to facilitate shipments from China to the Philippines.</p><p>We provide customers with <b>shipment coordination, warehouse assignment, cargo identification, shipping information, and customer support</b> throughout the process.</p></> },
  { question: "What happens if my shipment is damaged or lost?", answer: <><p><b>KargoDoor offers full coverage for eligible shipments, subject to verification and applicable coverage terms and exclusions.</b></p><p>Please keep your <b>photos, receipts, invoices, shipment records, and other supporting documents</b>, as these may be required for verification and processing.</p><p><b>MESSAGE KARGODOOR RIGHT AWAY SO WE CAN ASSIST YOU.</b></p></> },
  { question: "What are your operating hours?", answer: <><p><b>8:00 AM–10:00 PM</b></p><p><b>7 Days a Week</b></p><p>You may message KargoDoor anytime. Our team will respond to inquiries during our operating hours.</p></> },
];

export default function FaqPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const regionId = useId();
  return <div className="kd-site-shell"><Header /><main className="kd-faq-page"><section className="kd-faq-intro" aria-labelledby="faq-title"><div className="kd-container kd-faq-container"><header className="kd-faq-heading"><h1 id="faq-title">FREQUENTLY ASKED QUESTIONS</h1><p>Everything you need to know about shipping with KargoDoor PH.</p></header><div className="kd-faq-listing">{faqs.map((faq, index) => { const isOpen = openIndex === index; const answerId = `${regionId}-${index}`; return <article className={`kd-faq-item${isOpen ? " is-open" : ""}`} key={faq.question}><h2><button type="button" aria-expanded={isOpen} aria-controls={answerId} onClick={() => setOpenIndex(isOpen ? null : index)}><span><b>{index + 1}.</b> {faq.question}</span><i aria-hidden="true">{isOpen ? "−" : "+"}</i></button></h2><div id={answerId} className="kd-faq-answer" aria-hidden={!isOpen}><div>{faq.answer}</div></div></article>; })}</div></div></section></main><Footer /></div>;
}
